name: Build and Deploy
on:
  push:
    branches:
      - prod

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup Bun environment
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.11 # or "latest", "canary", <sha>

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.bun
          key: ${{ runner.os }}-bun-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install

      - name: Build static files
        run: bun run build

      - name: Deploy to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
            server: ${{secrets.FTP_SERVER}}
            username: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWORD }}
            local-dir: /out/
            server-dir: '/public_html/beta/'
